[package]
name = "completions"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenvy = "0.15.7"
rs_openai = {path = "../../rs_openai"}
tokio = { version = "1.26.0", features = ["full"] }
