[workspace]
members = [
    "audio",
    "chat",
    "completions",
    "edits",
    "embeddings",
    "engines",
    "files",
    "fine_tunes",
    "images",
    "models",
    "moderations",
]
resolver = "2"